# Generated by Django 5.1.6 on 2025-04-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deepseek_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
