# Generated by Django 5.1.6 on 2025-05-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_rename_ai_content_message_gemini_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="merged_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
